# Generated by Django 4.0.4 on 2022-06-29 00:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='The name of the account owner', max_length=100)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(help_text='Date the transaction was posted on the account.')),
                ('amount', models.DecimalField(decimal_places=2, help_text='The transaction amount. Positive amounts are deposits or transfers into the account while negative amounts are payments or transfers out of the account.', max_digits=15)),
                ('description', models.CharField(help_text='Original description of the transaction as reported by the provider.', max_length=100)),
                ('transaction_category', models.CharField(choices=[('ATM', 'Atm'), ('BILL_PAYMENT', 'Bill Payment'), ('CASH', 'Cash'), ('CASHBACK', 'Cashback'), ('CHEQUE', 'Cheque'), ('CORRECTION', 'Correction'), ('CREDIT', 'Credit'), ('DIRECT_DEBIT', 'Direct_Debit'), ('DIVIDEND', 'Dividend'), ('FEE_CHARGE', 'Fee_Charge'), ('INTEREST', 'Interest'), ('OTHER', 'Other'), ('PURCHASE', 'Purchase'), ('STANDING_ORDER', 'Standing Order'), ('TRANSFER', 'Transfer'), ('DEBIT', 'Debit'), ('UNKNOWN', 'Unknown')], max_length=20)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.account')),
            ],
        ),
    ]
